# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 600)
        MainWindow.setMaximumSize(QtCore.QSize(1000, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(1000, 600))
        self.centralwidget.setMaximumSize(QtCore.QSize(1000, 600))
        self.centralwidget.setObjectName("centralwidget")
        self.header_widget = QtWidgets.QWidget(self.centralwidget)
        self.header_widget.setGeometry(QtCore.QRect(-1, -1, 1001, 91))
        self.header_widget.setStyleSheet("background: rgb(23,154,195);\n"
"background: radial-gradient(circle, rgba(23,154,195,1) 0%, rgba(33,33,33,1) 100%);")
        self.header_widget.setObjectName("header_widget")
        self.close_btn = QtWidgets.QLabel(self.header_widget)
        self.close_btn.setGeometry(QtCore.QRect(950, 20, 30, 31))
        self.close_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.close_btn.setObjectName("close_btn")
        self.minimize_btn = QtWidgets.QLabel(self.header_widget)
        self.minimize_btn.setGeometry(QtCore.QRect(910, 20, 30, 30))
        self.minimize_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.minimize_btn.setObjectName("minimize_btn")
        self.header_img = QtWidgets.QLabel(self.header_widget)
        self.header_img.setGeometry(QtCore.QRect(0, 0, 1001, 91))
        self.header_img.setObjectName("header_img")
        self.logo = QtWidgets.QLabel(self.header_widget)
        self.logo.setGeometry(QtCore.QRect(20, 10, 191, 71))
        self.logo.setObjectName("logo")
        self.header_img.raise_()
        self.minimize_btn.raise_()
        self.close_btn.raise_()
        self.logo.raise_()
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 140, 1001, 461))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setIconSize(QtCore.QSize(64, 64))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.close_btn.setText(_translate("MainWindow", "картинка2"))
        self.minimize_btn.setText(_translate("MainWindow", "карти"))
        self.header_img.setText(_translate("MainWindow", "TextLabel"))
        self.logo.setText(_translate("MainWindow", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
